apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: world-countries
  name: world-countries
spec:
  replicas: 2
  selector:
    matchLabels:
      app: world-countries
  strategy: {}
  template:
    metadata:
      labels:
        app: world-countries
    spec:
      containers:
      - image: asia-docker.pkg.dev/qwiklabs-gcp-03-60ac62ad23be/testing/world-app@sha256:2941b49aff900cfe0ebac9a1fc7c924c638ddd021823de78bceee4f3857a361d
        name: world-countries
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: world-countries-secret
              key: MONGO_URI
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: world-countries-secret
              key: MONGO_USERNAME
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: world-countries-secret
              key: MONGO_PASSWORD
        resources: {}
status: {}
