---
apiVersion: bitnami.com/v1alpha1
kind: Secret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: world-countries-secret
spec:
  stringData:
    MONGO_PASSWORD: "root"
    MONGO_URI: "mongodb+srv://supercluster.d83jj.mongodb.net/superData"
    MONGO_USERNAME: "root"
      name: world-countries-secret
    type: Opaque
